// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2hsNPYH34YmJs55mD26fsULceSNRonTU',
    appId: '1:82325824078:web:760440e2557801d2d6991f',
    messagingSenderId: '82325824078',
    projectId: 'gestionticket-b8cfb',
    authDomain: 'gestionticket-b8cfb.firebaseapp.com',
    storageBucket: 'gestionticket-b8cfb.appspot.com',
    measurementId: 'G-TZH4DV7KCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHIDY9EAIA0Mq1s7ET-sG32G4ahP556E0',
    appId: '1:82325824078:android:598360379594d193d6991f',
    messagingSenderId: '82325824078',
    projectId: 'gestionticket-b8cfb',
    storageBucket: 'gestionticket-b8cfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAITauzDHgGDAvpww-WndMiq-desh1EO7g',
    appId: '1:82325824078:ios:5332ca33a4bd2213d6991f',
    messagingSenderId: '82325824078',
    projectId: 'gestionticket-b8cfb',
    storageBucket: 'gestionticket-b8cfb.appspot.com',
    iosBundleId: 'com.example.gestionTicket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAITauzDHgGDAvpww-WndMiq-desh1EO7g',
    appId: '1:82325824078:ios:5332ca33a4bd2213d6991f',
    messagingSenderId: '82325824078',
    projectId: 'gestionticket-b8cfb',
    storageBucket: 'gestionticket-b8cfb.appspot.com',
    iosBundleId: 'com.example.gestionTicket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2hsNPYH34YmJs55mD26fsULceSNRonTU',
    appId: '1:82325824078:web:3a5229a6c4448a70d6991f',
    messagingSenderId: '82325824078',
    projectId: 'gestionticket-b8cfb',
    authDomain: 'gestionticket-b8cfb.firebaseapp.com',
    storageBucket: 'gestionticket-b8cfb.appspot.com',
    measurementId: 'G-9R8VDVSPLP',
  );
}
